import {iSura} from "@/entities/Sura/model/types/surah.ts";

export const surahes: iSura[] = [
    {
        id: 78,
        revelation_place: "makkah",
        revelation_order: 80,
        bismillah_pre: true,
        name_simple: "An-Naba",
        name_complex: "An-Naba",
        name: "Ан-Наба",
        name_arabic: "النبإ",
        verses_count: 40,
        pages: [582, 583],
        translated_name: {
            language_name: "russian",
            name: "Весть",
        },
    },
    {
        id: 79,
        revelation_place: "makkah",
        revelation_order: 81,
        bismillah_pre: true,
        name_simple: "An-Nazi'at",
        name_complex: "An-Nāzi`āt",
        name: "Ан-Назиат",
        name_arabic: "النازعات",
        verses_count: 46,
        pages: [583, 584],
        translated_name: {
            language_name: "russian",
            name: "Исторгающие",
        },
    },
    {
        id: 80,
        revelation_place: "makkah",
        revelation_order: 24,
        bismillah_pre: true,
        name_simple: "'Abasa",
        name_complex: "`Abasa",
        name: "Абаса",
        name_arabic: "عبس",
        verses_count: 42,
        pages: [585, 585],
        translated_name: {
            language_name: "russian",
            name: "Нахмурился",
        },
    },
    {
        id: 81,
        revelation_place: "makkah",
        revelation_order: 7,
        bismillah_pre: true,
        name_simple: "At-Takwir",
        name_complex: "At-Takwīr",
        name: "Ат-Таквир",
        name_arabic: "التكوير",
        verses_count: 29,
        pages: [586, 586],
        translated_name: {
            language_name: "russian",
            name: "Скручивание",
        },
    },
    {
        id: 82,
        revelation_place: "makkah",
        revelation_order: 82,
        bismillah_pre: true,
        name_simple: "Al-Infitar",
        name_complex: "Al-'Infiţār",
        name: "Ал-Инфитор",
        name_arabic: "الإنفطار",
        verses_count: 19,
        pages: [587, 587],
        translated_name: {
            language_name: "russian",
            name: "Раскалывание",
        },
    },
    {
        id: 83,
        revelation_place: "makkah",
        revelation_order: 86,
        bismillah_pre: true,
        name_simple: "Al-Mutaffifin",
        name_complex: "Al-Muţaffifīn",
        name: "Ал-Мутоффифин",
        name_arabic: "المطففين",
        verses_count: 36,
        pages: [587, 589],
        translated_name: {
            language_name: "russian",
            name: "Обвешивающие",
        },
    },
    {
        id: 84,
        revelation_place: "makkah",
        revelation_order: 83,
        bismillah_pre: true,
        name_simple: "Al-Inshiqaq",
        name_complex: "Al-'Inshiqāq",
        name: "Ал-Иншикок",
        name_arabic: "الإنشقاق",
        verses_count: 25,
        pages: [589, 589],
        translated_name: {
            language_name: "russian",
            name: "Разверзнется",
        },
    },
    {
        id: 85,
        revelation_place: "makkah",
        revelation_order: 27,
        bismillah_pre: true,
        name_simple: "Al-Buruj",
        name_complex: "Al-Burūj",
        name: "Ал-Бурудж",
        name_arabic: "البروج",
        verses_count: 22,
        pages: [590, 590],
        translated_name: {
            language_name: "russian",
            name: "Созвездия Зодиака",
        },
    },
    {
        id: 86,
        revelation_place: "makkah",
        revelation_order: 36,
        bismillah_pre: true,
        name_simple: "At-Tariq",
        name_complex: "Aţ-Ţāriq",
        name: "Ат-Торикъ",
        name_arabic: "الطارق",
        verses_count: 17,
        pages: [591, 591],
        translated_name: {
            language_name: "russian",
            name: "Ночной путник",
        },
    },
    {
        id: 87,
        revelation_place: "makkah",
        revelation_order: 8,
        bismillah_pre: true,
        name_simple: "Al-A'la",
        name_complex: "Al-'A`lá",
        name: "Ал-Аъля",
        name_arabic: "الأعلى",
        verses_count: 19,
        pages: [591, 592],
        translated_name: {
            language_name: "russian",
            name: "Всевышний",
        },
    },
    {
        id: 88,
        revelation_place: "makkah",
        revelation_order: 68,
        bismillah_pre: true,
        name_simple: "Al-Ghashiyah",
        name_complex: "Al-Ghāshiyah",
        name: "Ал-Гошийах",

        name_arabic: "الغاشية",
        verses_count: 26,
        pages: [592, 592],
        translated_name: {
            language_name: "russian",
            name: "Покрывающее",
        },
    },
    {
        id: 89,
        revelation_place: "makkah",
        revelation_order: 10,
        bismillah_pre: true,
        name_simple: "Al-Fajr",
        name_complex: "Al-Fajr",
        name: "Ал-Фаджр",
        name_arabic: "الفجر",
        verses_count: 30,
        pages: [593, 594],
        translated_name: {
            language_name: "russian",
            name: "Заря",
        },
    },
    {
        id: 90,
        revelation_place: "makkah",
        revelation_order: 35,
        bismillah_pre: true,
        name_simple: "Al-Balad",
        name_complex: "Al-Balad",
        name: "Ал-Балад",
        name_arabic: "البلد",
        verses_count: 20,
        pages: [594, 594],
        translated_name: {
            language_name: "russian",
            name: "Город",
        },
    },
    {
        id: 91,
        revelation_place: "makkah",
        revelation_order: 26,
        bismillah_pre: true,
        name_simple: "Ash-Shams",
        name_complex: "Ash-Shams",
        name: "Аш-Шамс",
        name_arabic: "الشمس",
        verses_count: 15,
        pages: [595, 595],
        translated_name: {
            language_name: "russian",
            name: "Солнце",
        },
    },
    {
        id: 92,
        revelation_place: "makkah",
        revelation_order: 9,
        bismillah_pre: true,
        name_simple: "Al-Layl",
        name_complex: "Al-Layl",
        name: "Ал-Лайл",
        name_arabic: "الليل",
        verses_count: 21,
        pages: [595, 596],
        translated_name: {
            language_name: "russian",
            name: "Ночь",
        },
    },
    {
        id: 93,
        revelation_place: "makkah",
        revelation_order: 11,
        bismillah_pre: true,
        name_simple: "Ad-Duhaa",
        name_complex: "Ađ-Đuĥaá",
        name: "Ад-Духьа",
        name_arabic: "الضحى",
        verses_count: 11,
        pages: [596, 596],
        translated_name: {
            language_name: "russian",
            name: "Утро",
        },
    },
    {
        id: 94,
        revelation_place: "makkah",
        revelation_order: 12,
        bismillah_pre: true,
        name_simple: "Ash-Sharh",
        name_complex: "Ash-Sharĥ",
        name: "Аш-Шарх1",
        name_arabic: "الشرح",
        verses_count: 8,
        pages: [596, 596],
        translated_name: {
            language_name: "russian",
            name: "Раскрытие",
        },
    },
    {
        id: 95,
        revelation_place: "makkah",
        revelation_order: 28,
        bismillah_pre: true,
        name_simple: "At-Tin",
        name_complex: "At-Tīn",
        name: "Ат-Тин",
        name_arabic: "التين",
        verses_count: 8,
        pages: [597, 597],
        translated_name: {
            language_name: "russian",
            name: "Смоковница",
        },
    },
    {
        id: 96,
        revelation_place: "makkah",
        revelation_order: 1,
        bismillah_pre: true,
        name_simple: "Al-'Alaq",
        name_complex: "Al-`Alaq",
        name: "Ал-Аляк",
        name_arabic: "العلق",
        verses_count: 19,
        pages: [597, 597],
        translated_name: {
            language_name: "russian",
            name: "Сгусток крови",
        },
    },
    {
        id: 97,
        revelation_place: "makkah",
        revelation_order: 25,
        bismillah_pre: true,
        name_simple: "Al-Qadr",
        name_complex: "Al-Qadr",
        name: "Ал-Къодр",
        name_arabic: "القدر",
        verses_count: 5,
        pages: [598, 598],
        translated_name: {
            language_name: "russian",
            name: "Предопределение",
        },
    },
    {
        id: 98,
        revelation_place: "madinah",
        revelation_order: 100,
        bismillah_pre: true,
        name_simple: "Al-Bayyinah",
        name_complex: "Al-Bayyinah",
        name: "Ал-Баййинах1",
        name_arabic: "البينة",
        verses_count: 8,
        pages: [598, 599],
        translated_name: {
            language_name: "russian",
            name: "Ясное знамение",
        },
    },
    {
        id: 99,
        revelation_place: "madinah",
        revelation_order: 93,
        bismillah_pre: true,
        name_simple: "Az-Zalzalah",
        name_complex: "Az-Zalzalah",
        name: "Аз-Залзала",
        name_arabic: "الزلزلة",
        verses_count: 8,
        pages: [599, 599],
        translated_name: {
            language_name: "russian",
            name: "Сотрясение",
        },
    },
    {
        id: 100,
        revelation_place: "makkah",
        revelation_order: 14,
        bismillah_pre: true,
        name_simple: "Al-'Adiyat",
        name_complex: "Al-`Ādiyāt",
        name: "Ал-Адият",
        name_arabic: "العاديات",
        verses_count: 11,
        pages: [599, 600],
        translated_name: {
            language_name: "russian",
            name: "Скачущие",
        },
    },
    {
        id: 101,
        revelation_place: "makkah",
        revelation_order: 30,
        bismillah_pre: true,
        name_simple: "Al-Qari'ah",
        name_complex: "Al-Qāri`ah",
        name: "Ал-Къори1ах1",
        name_arabic: "القارعة",
        verses_count: 11,
        pages: [600, 600],
        translated_name: {
            language_name: "russian",
            name: "Великое бедствие",
        },
    },
    {
        id: 102,
        revelation_place: "makkah",
        revelation_order: 16,
        bismillah_pre: true,
        name_simple: "At-Takathur",
        name_complex: "At-Takāthur",
        name: "Ат-Такасур",

        name_arabic: "التكاثر",
        verses_count: 8,
        pages: [600, 600],
        translated_name: {
            language_name: "russian",
            name: "Страсть к приумножению",
        },
    },
    {
        id: 103,
        revelation_place: "makkah",
        revelation_order: 13,
        bismillah_pre: true,
        name_simple: "Al-'Asr",
        name_complex: "Al-`Aşr",
        name: "Ал-Аср",

        name_arabic: "العصر",
        verses_count: 3,
        pages: [601, 601],
        translated_name: {
            language_name: "russian",
            name: "Предвечернее время",
        },
    },
    {
        id: 104,
        revelation_place: "makkah",
        revelation_order: 32,
        bismillah_pre: true,
        name_simple: "Al-Humazah",
        name_complex: "Al-Humazah",
        name: "Ал-Хумазах",

        name_arabic: "الهمزة",
        verses_count: 9,
        pages: [601, 601],
        translated_name: {
            language_name: "russian",
            name: "Хулитель",
        },
    },
    {
        id: 105,
        revelation_place: "makkah",
        revelation_order: 19,
        bismillah_pre: true,
        name_simple: "Al-Fil",
        name_complex: "Al-Fīl",
        name: "Ал-Фил",

        name_arabic: "الفيل",
        verses_count: 5,
        pages: [601, 601],
        translated_name: {
            language_name: "russian",
            name: "Слон",
        },
    },
    {
        id: 106,
        revelation_place: "makkah",
        revelation_order: 29,
        bismillah_pre: true,
        name_simple: "Quraysh",
        name_complex: "Quraysh",
        name: "Къурайш",

        name_arabic: "قريش",
        verses_count: 4,
        pages: [602, 602],
        translated_name: {
            language_name: "russian",
            name: "Курейшиты",
        },
    },
    {
        id: 107,
        revelation_place: "makkah",
        revelation_order: 17,
        bismillah_pre: true,
        name_simple: "Al-Ma'un",
        name_complex: "Al-Mā`ūn",
        name: "Ал-Ма1ун",

        name_arabic: "الماعون",
        verses_count: 7,
        pages: [602, 602],
        translated_name: {
            language_name: "russian",
            name: "Мелочь",
        },
    },
    {
        id: 108,
        revelation_place: "makkah",
        revelation_order: 15,
        bismillah_pre: true,
        name_simple: "Al-Kawthar",
        name_complex: "Al-Kawthar",
        name: "Ал-Кавсар",

        name_arabic: "الكوثر",
        verses_count: 3,
        pages: [602, 602],
        translated_name: {
            language_name: "russian",
            name: "Изобилие",
        },
    },
    {
        id: 109,
        revelation_place: "makkah",
        revelation_order: 18,
        bismillah_pre: true,
        name_simple: "Al-Kafirun",
        name_complex: "Al-Kāfirūn",
        name: "Ал-Кафирун",

        name_arabic: "الكافرون",
        verses_count: 6,
        pages: [603, 603],
        translated_name: {
            language_name: "russian",
            name: "Неверующие",
        },
    },
    {
        id: 110,
        revelation_place: "madinah",
        revelation_order: 114,
        bismillah_pre: true,
        name_simple: "An-Nasr",
        name_complex: "An-Naşr",
        name: "Ан-Наср",

        name_arabic: "النصر",
        verses_count: 3,
        pages: [603, 603],
        translated_name: {
            language_name: "russian",
            name: "Помощь",
        },
    },
    {
        id: 111,
        revelation_place: "makkah",
        revelation_order: 6,
        bismillah_pre: true,
        name_simple: "Al-Masad",
        name_complex: "Al-Masad",
        name: "Ал-Масад",

        name_arabic: "المسد",
        verses_count: 5,
        pages: [603, 603],
        translated_name: {
            language_name: "russian",
            name: "Пальмовые волокна",
        },
    },
    {
        id: 112,
        revelation_place: "makkah",
        revelation_order: 22,
        bismillah_pre: true,
        name_simple: "Al-Ikhlas",
        name_complex: "Al-'Ikhlāş",
        name: "Ал-Ихляс",
        name_arabic: "الإخلاص",
        verses_count: 4,
        pages: [604, 604],
        translated_name: {
            language_name: "russian",
            name: "Очищение веры",
        },
    },
    {
        id: 113,
        revelation_place: "makkah",
        revelation_order: 20,
        bismillah_pre: true,
        name_simple: "Al-Falaq",
        name_complex: "Al-Falaq",
        name: "Ал-Фалякъ",
        name_arabic: "الفلق",
        verses_count: 5,
        pages: [604, 604],
        translated_name: {
            language_name: "russian",
            name: "Рассвет",
        },
    },
    {
        id: 114,
        revelation_place: "makkah",
        revelation_order: 21,
        bismillah_pre: true,
        name_simple: "An-Nas",
        name_complex: "An-Nās",
        name: "Ан-Нас",
        name_arabic: "الناس",
        verses_count: 6,
        pages: [604, 604],
        translated_name: {
            language_name: "russian",
            name: "Люди",
        },
    },
];
